### ISSUE TITLE
*figure captions for all figures

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/Basics#12]
A. Items which MUST be addressed to meet Ontario accessibility standards
5. Figure captions should be provided for all figures

**Comment by andrew-edwards** [comment]
So adding the fig caption seems to stop the alt text from popping up (e.g. your Fig 4.1). Is that okay? Actually a good thing because the alt text pop up does get in the way a bit.

So as long as the screen readers still read out the alt text, then that's great, and better than what I thought would happen.

**Comment by andrew-edwards** [comment]
Done for Git and Rmarkdown modules.

**Comment by kcudding** [comment]
I checked and the alt text is there as per accessibility. I thinks this is all good.
